# Do not edit this file by hand. It is seeded from packaging/ttdl.rb in sadorlovsky/ttdl, and its
# url and sha256 are rewritten here by that repository's release workflow every time a tag is
# pushed. Any other change belongs in the source copy, or the next release will undo it.
#
class Ttdl < Formula
  include Language::Python::Virtualenv

  desc "Archive a whole TikTok account: videos, photo carousels, metadata, thumbnails"
  homepage "https://ttdl.orlovsky.dev"
  url "https://github.com/sadorlovsky/ttdl/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "d033f803353629aaedcd137d10217a09a7b410d03a4242fb1d46bc509d5822b9"
  license "MIT"
  head "https://github.com/sadorlovsky/ttdl.git", branch: "main"

  # yt-dlp is the extractor and is not optional. ffmpeg is needed by a default run, which
  # measures loudness; --no-loudness is the only way around it. rclone is deliberately absent:
  # only push and check --remote want it, and most archives never leave the machine.
  depends_on "ffmpeg"
  depends_on "python@3.13"
  depends_on "yt-dlp"

  def install
    virtualenv_install_with_resources
  end

  def caveats
    <<~EOS
      Storage commands need rclone, which is not a dependency:
        brew install rclone

      Shell completion:
        ttdl completion zsh > "$(brew --prefix)/share/zsh/site-functions/_ttdl"

      `ttdl doctor` checks the rest.
    EOS
  end

  test do
    assert_match "ttdl #{version}", shell_output("#{bin}/ttdl --version")
    assert_match "COMMAND", shell_output("#{bin}/ttdl --help")
  end
end
